name: dart_ytmusic_api
description: Unofficial YouTube Music Api for dart 
version: 1.2.1
repository: https://github.com/MusilyApp/dart_ytmusic_api

environment:
  sdk: ^3.4.3

dependencies:
  cookie_jar: 
  dio: 
  html:
  http:
  intl: 

dev_dependencies:
  lints: 
  test: 
